### PR TITLE
Clean up isVisibilityBridge, and fix NPE in it.  Fixes #372.

### LINKED ISSUE #372: Throwable thrown while handling command: java.lang.NullPointerException
1) set up the randoop pascali coverage suite => https://gitlab.cs.washington.edu/randoop/pascali-coverage
2) cd to the directory established in step (1)
3) cd integration-test2
4) run './run_randoop.py scijava-common'
5) the various output files will be in integration-test2/corpus/scijava-common/dljc-out
6) i have attached randoop.log from that directory
[randoop.log](https://github.com/randoop/randoop/files/2027530/randoop.log)

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

File: src/main/java/randoop/reflection/DefaultReflectionPredicate.java [hunk 1]
```diff
@@ -159,32 +158,46 @@ private boolean discardBridge(Method m) {
...
+      c = c.getSuperclass();
+    }
+    // System.out.printf("Never found superclass with definition of %s%n", m);
+    return false;
+  }
+
+  /**
+   * Returns true if the class defines the given method, not as a bridge method. Returns false if
+   * the class does not define the given method, or if the class defines the method as a bridge
+   * method. Ifnores inheritance of methods.
```
Comment (markro49) [inline src/main/java/randoop/reflection/DefaultReflectionPredicate.java]: Typo? Ifnores => Ignores
